# config/zed_yaml
# Parameters for Stereolabs ZED camera
---
/**:
    ros__parameters:
        general:
            camera_model: "zed2i"
            camera_name: "zed" # usually overwritten by launch file

        depth:
            min_depth: 0.2 
            max_depth: 10.0
