vehicle_control:
  ros_parameters:

    # RC signal
    steering_min_pwm: 1100
    steering_mid_pwm: 1515
    steering_max_pwm: 1900
    throttle_min_pwm: 1000
    throttle_mid_pwm: 1500
    throttle_max_pwm: 2000
    mode_min_pwm: 1000
    mode_mid_pwm: 1500
    mode_max_pwm: 2000

    # Vesc
    # From vesc_ros2
    port: "/dev/vesc"
    brake_max: 200000.0
    brake_min: -20000.0
    current_max: 100.0
    current_min: 0.0
    duty_cycle_max: 0.0
    duty_cycle_min: 0.0
    position_max: 0.0
    position_min: 0.0
    servo_max: 0.85
    servo_min: 0.15
    speed_max: 25000.0
    speed_min: -25000.0
    
    # From mxck
    # servo value reaches from 0 to 1 (/commands/servo/position)
    # select the min and max value so that the steering does not block
    # select the mid value so that the vehicle drives a straight line
    servo_max: 0.9
    servo_min: 0.1
    servo_mid: 0.502
    wheelbase: 0.36

    # use the min and max servo position from above to drive a left and right circle
    lr_rmin: 0.76 # measure the left radius [meter] (measured from center front axle)
    rr_rmin: 0.82 # measure the right radius [meter]

    # drive with constant erpm over a fixed distance and measure the time the car takes
    # ros2 topic pub -r 5 /commands/motor/speed {erpm} e.g. erpm = 4000
    # from this the speed is calculated speed (m/s) = distance (m) / time (s)
    # calculate speed_to_erpm_gain = erpm / speed
    speed_to_erpm_gain: 10000 ## 3786 Original (TODO: measure a new erpm using new vesc config)

    # Servo
    # the maximum steering angle is determined from the measured left and right radius and the wheelbase
    # see ackermann_to_vesc.py
    servo_rad_min: -0.442
    servo_rad_mid: 0
    servo_rad_max: 0.442

    # Similar to real vehicles, carkits cannot drive infinitely slow. 
    # That is why we set a minimum starting speed.
    # True sensorless commutation is possible only with motor speeds of 500-1000 rpm and up.
    speed_clip: 0.2 # the carkit starts with +/- ... m/s 
    

    # Manual control
    rc_speed_axis: 1
    rc_steering_axis: 0
    rc_deadman_button: 0
    joy_speed_axis: 1
    joy_steering_axis: 3
    joy_deadman_button: 4 

    # Deadzones
    speed_deadzone: 0.001
    steer_deadzone: 0.001
